
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int llaveC = 5;
  public static final int PSstring = 11;
  public static final int llaveA = 4;
  public static final int ptoComa = 2;
  public static final int parC = 7;
  public static final int cadena = 12;
  public static final int parA = 6;
  public static final int decimal = 14;
  public static final int PSdouble = 10;
  public static final int EOF = 0;
  public static final int entero = 13;
  public static final int error = 1;
  public static final int PSint = 9;
  public static final int identificador = 15;
  public static final int PSprint = 8;
  public static final int igual = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ptoComa",
  "igual",
  "llaveA",
  "llaveC",
  "parA",
  "parC",
  "PSprint",
  "PSint",
  "PSdouble",
  "PSstring",
  "cadena",
  "entero",
  "decimal",
  "identificador"
  };
}

